### ISSUE TITLE
好像改了hosts并不能用啊

### ISSUE THREAD

**Issue by j20120307** [JixunMoe/unblock-163#2]

**Comment by jixunmoe** [comment]
请尝试清空浏览器、DNS 缓存，另外请报告一下你的操作系统。

**Comment by j20120307** [comment]
OS X EI Capitan
Version 10.11.1
dscacheutil -flushcache
浏览器缓存是只要cache images and files吗？
另外是mac客户端的不能用 网页版的用tampermonkey能听一些 我试试看你的gist

**Comment by jixunmoe** [comment]
脚本仅限网页版 不支援客户端。

另外网易好像屏蔽了海外用户的播放功能，脚本应该能解锁这部分功能。

**Comment by j20120307** [comment]
网页版已经能正常使用，客户端目前只能改dns了

**Comment by jixunmoe** [comment]
如果 dns 方法可以用的话 那么 Hosts 应该也可以用的。

**Comment by j20120307** [comment]
现在客户端只能用Proxifier的方式解决 不知道以后会有什么方法不

**Comment by jixunmoe** [comment]
不知道了，关 issue。

我现在都只用网页版
