### ISSUE TITLE
Add one more IP address

### ISSUE THREAD

**Issue by buzouxun** [JixunMoe/unblock-163#3]
198.47.104.134 m10.music.126.net

我试了加上这个之后，就可以用了，不然挺不起来。。。但不大清楚为什么

**Comment by jixunmoe** [comment]
忘了同步更新了 等下上电脑加上

**Comment by jixunmoe** [comment]
https://github.com/JixunMoe/cuwcl4c/issues/14#issuecomment-161939835

暂时可以参考此处讨论。。等下更新过来

**Comment by buzouxun** [comment]
好的谢谢~~ 我有个小白问题：如果使用cuwcl4c，是不是就不用改windows 上 本地的 Hosts文件了？

**Comment by jixunmoe** [comment]
是的 至少我当时测试的时候是这样。
因为会随机将歌曲跳转至网宿(感谢 @typcn 的提示，这个是网易用的 CDN)的CDN服务器反向代理。

还有疑问的话欢迎重新打开/新建 Issue :D

另外我现在暂时在国内，无法进行测试了..

**Comment by typcn** [comment]
并不是反代。。。这就是一个CDN服务器，因为DNS可能会有解析误差，所以说，在某个节点压力过高或者是IP误差过大时，他就会 302 到指定的 IP。

格式就是 http://ip/域名

例如： http://ws.acgvideo.com  http://video1.tycdn.net

这是网宿 CDN 自带的 feature，在用户的控制面板里面就可以开启或者关闭这个功能

**Comment by jixunmoe** [comment]
原来如此 我并没用过网宿 :D
