### ISSUE TITLE
Found a way to unlock songs whose play buttons are disabled

### ISSUE THREAD

**Issue by EraserKing** [JixunMoe/unblock-163#4]
I didn't find your mail address so I'd like to contact you here.

With the help of your script https://github.com/JixunMoe/cuwcl4c, there's a way to play songs whose play buttons are disabled. Briefly speaking, replace the gray play button first (with the normal blue one) first, modify the return value of some AJAX requests (your script is necessary as the it hacks the URL to playback for the player, while the original one gets a bad URL).

Tested this with lots of songs and it succeeds, so I just want to make this way automatic. Nevertheless, I am not able to finish this, as it's beyond my current JavaScript skill, and I don't have much spare time now.
I was wondering if you're interested in this... Thanks.

**Comment by jixunmoe** [comment]
The script you mentioned already enables disabled songs, I just keep it look disabled as you would normally expected, so I hope 163's developer wouldn't notice it.

However I'm back China right now for a short holiday, I wouldn't be able to test it if is broken again.

**Comment by EraserKing** [comment]
Unfortunately, it's not working now... It looks disabled and behaves disabled also. Clicking it gets no response. As you have come back to China, you may be able to try it yourself, which would just take several minutes.

Actually, a simple replacing play button (as your script does) is just a start. It would just lead to a dialog telling you the resource is not available.
Some more modification needs to be done, which has been finished and proved functioning.

Not sure if you're going to merge my changes. If so I'll make a pull request, or fork your project if not.

Thanks.

**Comment by jixunmoe** [comment]
If you submit a PR I'd like to review the code and merge it :D

**Comment by jixunmoe** [comment]
They have changed the methods location, to be fixed.

**Comment by jixunmoe** [comment]
It seems they've moved method names back, close issue.
