### ISSUE TITLE
 似乎已经失效？

### ISSUE THREAD

**Issue by fireattack** [JixunMoe/unblock-163#5]
点歌曲列表中歌曲前的播放按钮依然会弹出“由于版权保护，您所在的地区暂时无法使用。”，点播放器上的播放按钮无反应

**Comment by jixunmoe** [comment]
我目前在国内  无法进行测试

请等我出来后继续修复问题 :D

**Comment by buzouxun** [comment]
@fireattack  我是改的HOSTS，然后配合JixunMoe/cuwcl4c，使用没有问题

**Comment by fireattack** [comment]
我在这里反馈的是扩展。

至于hosts，根据 https://github.com/JixunMoe/unblock-163 这里的说明和本扩展是两种不同的方式吧。改了Hosts自然可以用了，但是和扩展没什么大关系。

**Comment by buzouxun** [comment]
@fireattack  不好意思，我没有表达清楚我的意思。。我是讲说目前jixunmoe没法修复扩展，同时如果你想现在就能使用163music，可以改的HOSTS并配合JixunMoe/cuwcl4c来就能用起来了，一个workaround
如果只改hosts，然后点击播放键我记得还是会弹出版权什么的pop up window，所以还要配合JixunMoe/cuwcl4c的海外用户选项。。

**Comment by fireattack** [comment]
@buzouxun 原来如此，多谢提醒！

**Comment by jixunmoe** [comment]
全线飘灰不可破，单纯替换 URL 不可行了。
